# Qwen3-32B 模型配置（Dense 模型）
name: "Qwen3-32B"

# 核心参数
max_seq_len: 40960
vocab_size: 151936
hidden_size: 5120
intermediate_size: 25600
num_layers: 64
num_attention_heads: 64
num_key_value_heads: 8
v_head_dim: 128
hidden_act: "silu"
norm_type: "rmsnorm"
rms_norm_eps: 1.0e-6
attention_bias: false
attention_dropout: 0.0

# RoPE 配置
RoPE:
  theta: 1000000.0
  max_position_embeddings: 40960
