# Qwen3-235B Benchmark
# 输入序列长度: 8K, 输出序列长度: 512

id: Qwen3-235B-S8K-O512
name: Qwen3-235B-S8K-O512

model:
  name: qwen3_235b
  hidden_size: 8192
  num_layers: 80
  num_dense_layers: 0
  num_moe_layers: 80
  num_heads: 64
  vocab_size: 151936
  dtype: bf16

  moe:
    num_routed_experts: 128
    num_shared_experts: 1
    num_activated_experts: 8
    intermediate_size: 2560

  ffn:
    intermediate_size: 29568

inference:
  batch_size: 4
  input_seq_length: 8192
  output_seq_length: 512
