name: SG2262
num_cores: 64
compute_tflops_fp8: 256
compute_tflops_bf16: 128
memory_capacity_gb: 32
memory_bandwidth_gbps: 819
memory_bandwidth_utilization: 0.85
lmem_capacity_mb: 128
lmem_bandwidth_gbps: 12000
cube_m: 16
cube_k: 32
cube_n: 8
sram_size_kb: 2048
sram_utilization: 0.45
lane_num: 16
align_bytes: 32
compute_dma_overlap_rate: 0.8
created_at: '2026-02-04T22:17:17.718932'
updated_at: '2026-02-04T22:17:17.718932'
