id: DeepSeek-V3.2-S512-O256-W16A16-B8
name: DeepSeek-V3.2-S512-O256-W16A16-B8
model: DeepSeek-V3.2
topology: P1-R1-B1-C8
inference:
  batch_size: 8
  input_seq_length: 512
  output_seq_length: 256
  weight_dtype: bf16
  activation_dtype: bf16
