id: DeepSeek-V3.2-671B-A37B-S512-O256-W8A8-B8
name: DeepSeek-V3.2-671B-A37B-S512-O256-W16A16-B8
model: DeepSeek-V3.2-671B-A37B
topology: P1-R1-B4-C32
inference:
  batch_size: 8
  input_seq_length: 512
  output_seq_length: 256
  weight_dtype: fp8
  activation_dtype: fp8
