name: P1-R1-B1-C8
pods:
- count: 1
  racks:
  - count: 1
    boards:
    - id: board_1
      name: Board
      u_height: 2
      count: 1
      chips:
      - name: SG2262
        count: 8
    total_u: 42
chips:
  SG2262:
    name: SG2262
    architecture: TPU_V7
    process: 7nm
    frequency_ghz: 1
    align_bytes: 32
    compute_dma_overlap_rate: 0.8
    compute_efficiency: 0.9
    cores:
      count: 4
      lanes_per_core: 64
    compute_units:
      cube:
        m: 16
        k: 32
        n: 8
        mac_per_lane:
          INT8: 1000
          FP8: 1000
          BF16: 500
          FP16: 500
          TF32: 250
          INT4: 2000
      vector:
        eu_per_lane:
          INT8: 64
          FP8: 64
          INT16: 32
          BF16: 32
          FP16: 32
          INT32: 16
          FP32: 16
    memory:
      gmem:
        type: LPDDR5
        capacity_gb: 64
        bandwidth_gbps: 273
        bandwidth_utilization: 0.85
        latency_ns: 100
      lmem:
        capacity_mb: 64
        bandwidth_gbps: 2000
        latency_ns: 1
        sram_utilization: 0.45
    dma_engines:
      gdma:
        bandwidth_gbps: 68
        startup_latency_ns: 100
        efficiency: 0.9
    interconnect:
      NoC:
        topology: Mesh
        bandwidth_gbps: 1000
        latency_ns: 10
interconnect:
  links:
    c2c:
      bandwidth_gbps: 400
      latency_us: 0.2
    b2b:
      bandwidth_gbps: 450
      latency_us: 0.35
    r2r:
      bandwidth_gbps: 200
      latency_us: 2
    p2p:
      bandwidth_gbps: 100
      latency_us: 5
  comm_params:
    bandwidth_utilization: 0.95
    sync_latency_us: 0
    switch_latency_us: 1
    cable_latency_us: 0.025
    memory_read_latency_us: 0.15
    memory_write_latency_us: 0.01
    noc_latency_us: 0.05
    die_to_die_latency_us: 0.04
