name: P1-R1-B1-C8
pod_count: 1
racks_per_pod: 1
rack_config:
  total_u: 42
  boards:
  - id: board_1
    name: Board
    u_height: 2
    count: 1
    chips:
    - name: SG2262
      count: 8
hardware_params:
  interconnect:
    c2c:
      bandwidth_gbps: 448
      latency_us: 0.2
    b2b:
      bandwidth_gbps: 450
      latency_us: 0.35
    r2r:
      bandwidth_gbps: 200
      latency_us: 2
    p2p:
      bandwidth_gbps: 100
      latency_us: 5
comm_latency_config:
  rtt_tp_us: 0.35
  rtt_ep_us: 0.85
  bandwidth_utilization: 0.95
  sync_latency_us: 0
  switch_delay_us: 1
  cable_delay_us: 0.025
  memory_read_latency_us: 0.15
  memory_write_latency_us: 0.01
  noc_latency_us: 0.05
  die_to_die_latency_us: 0.04
