name: P1-R1-B4-C32
pods:
- count: 1
  racks:
  - count: 1
    boards:
    - id: board_1
      name: Board
      u_height: 2
      count: 4
      chips:
      - name: SG2262
        count: 8
        preset_id: SG2262
    total_u: 42
chips:
  SG2262:
    name: SG2262
    architecture: TPU_V7
    process: 7nm
    frequency_ghz: 1
    align_bytes: 32
    compute_dma_overlap_rate: 0.8
    compute_efficiency: 0.9
    cores:
      count: 4
      lanes_per_core: 64
    compute_units:
      cube:
        m: 16
        k: 32
        n: 8
        mac_per_lane:
          INT8: 1000
          FP8: 1000
          BF16: 500
          FP16: 500
          TF32: 250
          INT4: 2000
      vector:
        eu_per_lane:
          INT8: 64
          FP8: 64
          INT16: 32
          BF16: 32
          FP16: 32
          INT32: 16
          FP32: 16
    memory:
      gmem:
        type: LPDDR5
        capacity_gb: 64
        bandwidth_gbps: 273
        bandwidth_utilization: 0.85
        latency_ns: 100
      lmem:
        capacity_mb: 64
        bandwidth_gbps: 2000
        latency_ns: 1
        sram_utilization: 0.45
    dma_engines:
      gdma:
        bandwidth_gbps: 68
        startup_latency_ns: 100
        efficiency: 0.9
    interconnect:
      NoC:
        topology: Mesh
        bandwidth_gbps: 1000
        latency_ns: 10
interconnect:
  links:
    c2c:
      bandwidth_gbps: 400
      latency_us: 0.2
    b2b:
      bandwidth_gbps: 450
      latency_us: 0.35
    r2r:
      bandwidth_gbps: 200
      latency_us: 2
    p2p:
      bandwidth_gbps: 100
      latency_us: 5
  comm_params:
    bandwidth_utilization: 0.95
    sync_latency_us: 0
    switch_latency_us: 1
    cable_latency_us: 0.025
    memory_read_latency_us: 0.15
    memory_write_latency_us: 0.01
    noc_latency_us: 0.05
    die_to_die_latency_us: 0.04
switch_config:
  switch_types:
  - id: switch_48
    name: Switch
    port_count: 48
  inter_pod:
    enabled: false
    layers: []
    downlink_redundancy: 1
    connect_to_upper_level: true
    keep_direct_topology: false
  inter_rack:
    enabled: false
    layers: []
    downlink_redundancy: 1
    connect_to_upper_level: true
    keep_direct_topology: false
  inter_board:
    enabled: false
    layers: []
    downlink_redundancy: 1
    connect_to_upper_level: true
    keep_direct_topology: false
    switch_position: top
    switch_u_height: 1
  inter_chip:
    enabled: false
    layers: []
    downlink_redundancy: 1
    connect_to_upper_level: true
    direct_topology: full_mesh
    keep_direct_topology: false
connections:
- source: pod_0/rack_0/board_0/chip_0
  target: pod_0/rack_0/board_0/chip_1
  type: c2c
- source: pod_0/rack_0/board_0/chip_0
  target: pod_0/rack_0/board_0/chip_2
  type: c2c
- source: pod_0/rack_0/board_0/chip_0
  target: pod_0/rack_0/board_0/chip_3
  type: c2c
- source: pod_0/rack_0/board_0/chip_0
  target: pod_0/rack_0/board_0/chip_4
  type: c2c
- source: pod_0/rack_0/board_0/chip_0
  target: pod_0/rack_0/board_0/chip_5
  type: c2c
- source: pod_0/rack_0/board_0/chip_0
  target: pod_0/rack_0/board_0/chip_6
  type: c2c
- source: pod_0/rack_0/board_0/chip_0
  target: pod_0/rack_0/board_0/chip_7
  type: c2c
- source: pod_0/rack_0/board_0/chip_1
  target: pod_0/rack_0/board_0/chip_2
  type: c2c
- source: pod_0/rack_0/board_0/chip_1
  target: pod_0/rack_0/board_0/chip_3
  type: c2c
- source: pod_0/rack_0/board_0/chip_1
  target: pod_0/rack_0/board_0/chip_4
  type: c2c
- source: pod_0/rack_0/board_0/chip_1
  target: pod_0/rack_0/board_0/chip_5
  type: c2c
- source: pod_0/rack_0/board_0/chip_1
  target: pod_0/rack_0/board_0/chip_6
  type: c2c
- source: pod_0/rack_0/board_0/chip_1
  target: pod_0/rack_0/board_0/chip_7
  type: c2c
- source: pod_0/rack_0/board_0/chip_2
  target: pod_0/rack_0/board_0/chip_3
  type: c2c
- source: pod_0/rack_0/board_0/chip_2
  target: pod_0/rack_0/board_0/chip_4
  type: c2c
- source: pod_0/rack_0/board_0/chip_2
  target: pod_0/rack_0/board_0/chip_5
  type: c2c
- source: pod_0/rack_0/board_0/chip_2
  target: pod_0/rack_0/board_0/chip_6
  type: c2c
- source: pod_0/rack_0/board_0/chip_2
  target: pod_0/rack_0/board_0/chip_7
  type: c2c
- source: pod_0/rack_0/board_0/chip_3
  target: pod_0/rack_0/board_0/chip_4
  type: c2c
- source: pod_0/rack_0/board_0/chip_3
  target: pod_0/rack_0/board_0/chip_5
  type: c2c
- source: pod_0/rack_0/board_0/chip_3
  target: pod_0/rack_0/board_0/chip_6
  type: c2c
- source: pod_0/rack_0/board_0/chip_3
  target: pod_0/rack_0/board_0/chip_7
  type: c2c
- source: pod_0/rack_0/board_0/chip_4
  target: pod_0/rack_0/board_0/chip_5
  type: c2c
- source: pod_0/rack_0/board_0/chip_4
  target: pod_0/rack_0/board_0/chip_6
  type: c2c
- source: pod_0/rack_0/board_0/chip_4
  target: pod_0/rack_0/board_0/chip_7
  type: c2c
- source: pod_0/rack_0/board_0/chip_5
  target: pod_0/rack_0/board_0/chip_6
  type: c2c
- source: pod_0/rack_0/board_0/chip_5
  target: pod_0/rack_0/board_0/chip_7
  type: c2c
- source: pod_0/rack_0/board_0/chip_6
  target: pod_0/rack_0/board_0/chip_7
  type: c2c
- source: pod_0/rack_0/board_1/chip_0
  target: pod_0/rack_0/board_1/chip_1
  type: c2c
- source: pod_0/rack_0/board_1/chip_0
  target: pod_0/rack_0/board_1/chip_2
  type: c2c
- source: pod_0/rack_0/board_1/chip_0
  target: pod_0/rack_0/board_1/chip_3
  type: c2c
- source: pod_0/rack_0/board_1/chip_0
  target: pod_0/rack_0/board_1/chip_4
  type: c2c
- source: pod_0/rack_0/board_1/chip_0
  target: pod_0/rack_0/board_1/chip_5
  type: c2c
- source: pod_0/rack_0/board_1/chip_0
  target: pod_0/rack_0/board_1/chip_6
  type: c2c
- source: pod_0/rack_0/board_1/chip_0
  target: pod_0/rack_0/board_1/chip_7
  type: c2c
- source: pod_0/rack_0/board_1/chip_1
  target: pod_0/rack_0/board_1/chip_2
  type: c2c
- source: pod_0/rack_0/board_1/chip_1
  target: pod_0/rack_0/board_1/chip_3
  type: c2c
- source: pod_0/rack_0/board_1/chip_1
  target: pod_0/rack_0/board_1/chip_4
  type: c2c
- source: pod_0/rack_0/board_1/chip_1
  target: pod_0/rack_0/board_1/chip_5
  type: c2c
- source: pod_0/rack_0/board_1/chip_1
  target: pod_0/rack_0/board_1/chip_6
  type: c2c
- source: pod_0/rack_0/board_1/chip_1
  target: pod_0/rack_0/board_1/chip_7
  type: c2c
- source: pod_0/rack_0/board_1/chip_2
  target: pod_0/rack_0/board_1/chip_3
  type: c2c
- source: pod_0/rack_0/board_1/chip_2
  target: pod_0/rack_0/board_1/chip_4
  type: c2c
- source: pod_0/rack_0/board_1/chip_2
  target: pod_0/rack_0/board_1/chip_5
  type: c2c
- source: pod_0/rack_0/board_1/chip_2
  target: pod_0/rack_0/board_1/chip_6
  type: c2c
- source: pod_0/rack_0/board_1/chip_2
  target: pod_0/rack_0/board_1/chip_7
  type: c2c
- source: pod_0/rack_0/board_1/chip_3
  target: pod_0/rack_0/board_1/chip_4
  type: c2c
- source: pod_0/rack_0/board_1/chip_3
  target: pod_0/rack_0/board_1/chip_5
  type: c2c
- source: pod_0/rack_0/board_1/chip_3
  target: pod_0/rack_0/board_1/chip_6
  type: c2c
- source: pod_0/rack_0/board_1/chip_3
  target: pod_0/rack_0/board_1/chip_7
  type: c2c
- source: pod_0/rack_0/board_1/chip_4
  target: pod_0/rack_0/board_1/chip_5
  type: c2c
- source: pod_0/rack_0/board_1/chip_4
  target: pod_0/rack_0/board_1/chip_6
  type: c2c
- source: pod_0/rack_0/board_1/chip_4
  target: pod_0/rack_0/board_1/chip_7
  type: c2c
- source: pod_0/rack_0/board_1/chip_5
  target: pod_0/rack_0/board_1/chip_6
  type: c2c
- source: pod_0/rack_0/board_1/chip_5
  target: pod_0/rack_0/board_1/chip_7
  type: c2c
- source: pod_0/rack_0/board_1/chip_6
  target: pod_0/rack_0/board_1/chip_7
  type: c2c
- source: pod_0/rack_0/board_2/chip_0
  target: pod_0/rack_0/board_2/chip_1
  type: c2c
- source: pod_0/rack_0/board_2/chip_0
  target: pod_0/rack_0/board_2/chip_2
  type: c2c
- source: pod_0/rack_0/board_2/chip_0
  target: pod_0/rack_0/board_2/chip_3
  type: c2c
- source: pod_0/rack_0/board_2/chip_0
  target: pod_0/rack_0/board_2/chip_4
  type: c2c
- source: pod_0/rack_0/board_2/chip_0
  target: pod_0/rack_0/board_2/chip_5
  type: c2c
- source: pod_0/rack_0/board_2/chip_0
  target: pod_0/rack_0/board_2/chip_6
  type: c2c
- source: pod_0/rack_0/board_2/chip_0
  target: pod_0/rack_0/board_2/chip_7
  type: c2c
- source: pod_0/rack_0/board_2/chip_1
  target: pod_0/rack_0/board_2/chip_2
  type: c2c
- source: pod_0/rack_0/board_2/chip_1
  target: pod_0/rack_0/board_2/chip_3
  type: c2c
- source: pod_0/rack_0/board_2/chip_1
  target: pod_0/rack_0/board_2/chip_4
  type: c2c
- source: pod_0/rack_0/board_2/chip_1
  target: pod_0/rack_0/board_2/chip_5
  type: c2c
- source: pod_0/rack_0/board_2/chip_1
  target: pod_0/rack_0/board_2/chip_6
  type: c2c
- source: pod_0/rack_0/board_2/chip_1
  target: pod_0/rack_0/board_2/chip_7
  type: c2c
- source: pod_0/rack_0/board_2/chip_2
  target: pod_0/rack_0/board_2/chip_3
  type: c2c
- source: pod_0/rack_0/board_2/chip_2
  target: pod_0/rack_0/board_2/chip_4
  type: c2c
- source: pod_0/rack_0/board_2/chip_2
  target: pod_0/rack_0/board_2/chip_5
  type: c2c
- source: pod_0/rack_0/board_2/chip_2
  target: pod_0/rack_0/board_2/chip_6
  type: c2c
- source: pod_0/rack_0/board_2/chip_2
  target: pod_0/rack_0/board_2/chip_7
  type: c2c
- source: pod_0/rack_0/board_2/chip_3
  target: pod_0/rack_0/board_2/chip_4
  type: c2c
- source: pod_0/rack_0/board_2/chip_3
  target: pod_0/rack_0/board_2/chip_5
  type: c2c
- source: pod_0/rack_0/board_2/chip_3
  target: pod_0/rack_0/board_2/chip_6
  type: c2c
- source: pod_0/rack_0/board_2/chip_3
  target: pod_0/rack_0/board_2/chip_7
  type: c2c
- source: pod_0/rack_0/board_2/chip_4
  target: pod_0/rack_0/board_2/chip_5
  type: c2c
- source: pod_0/rack_0/board_2/chip_4
  target: pod_0/rack_0/board_2/chip_6
  type: c2c
- source: pod_0/rack_0/board_2/chip_4
  target: pod_0/rack_0/board_2/chip_7
  type: c2c
- source: pod_0/rack_0/board_2/chip_5
  target: pod_0/rack_0/board_2/chip_6
  type: c2c
- source: pod_0/rack_0/board_2/chip_5
  target: pod_0/rack_0/board_2/chip_7
  type: c2c
- source: pod_0/rack_0/board_2/chip_6
  target: pod_0/rack_0/board_2/chip_7
  type: c2c
- source: pod_0/rack_0/board_3/chip_0
  target: pod_0/rack_0/board_3/chip_1
  type: c2c
- source: pod_0/rack_0/board_3/chip_0
  target: pod_0/rack_0/board_3/chip_2
  type: c2c
- source: pod_0/rack_0/board_3/chip_0
  target: pod_0/rack_0/board_3/chip_3
  type: c2c
- source: pod_0/rack_0/board_3/chip_0
  target: pod_0/rack_0/board_3/chip_4
  type: c2c
- source: pod_0/rack_0/board_3/chip_0
  target: pod_0/rack_0/board_3/chip_5
  type: c2c
- source: pod_0/rack_0/board_3/chip_0
  target: pod_0/rack_0/board_3/chip_6
  type: c2c
- source: pod_0/rack_0/board_3/chip_0
  target: pod_0/rack_0/board_3/chip_7
  type: c2c
- source: pod_0/rack_0/board_3/chip_1
  target: pod_0/rack_0/board_3/chip_2
  type: c2c
- source: pod_0/rack_0/board_3/chip_1
  target: pod_0/rack_0/board_3/chip_3
  type: c2c
- source: pod_0/rack_0/board_3/chip_1
  target: pod_0/rack_0/board_3/chip_4
  type: c2c
- source: pod_0/rack_0/board_3/chip_1
  target: pod_0/rack_0/board_3/chip_5
  type: c2c
- source: pod_0/rack_0/board_3/chip_1
  target: pod_0/rack_0/board_3/chip_6
  type: c2c
- source: pod_0/rack_0/board_3/chip_1
  target: pod_0/rack_0/board_3/chip_7
  type: c2c
- source: pod_0/rack_0/board_3/chip_2
  target: pod_0/rack_0/board_3/chip_3
  type: c2c
- source: pod_0/rack_0/board_3/chip_2
  target: pod_0/rack_0/board_3/chip_4
  type: c2c
- source: pod_0/rack_0/board_3/chip_2
  target: pod_0/rack_0/board_3/chip_5
  type: c2c
- source: pod_0/rack_0/board_3/chip_2
  target: pod_0/rack_0/board_3/chip_6
  type: c2c
- source: pod_0/rack_0/board_3/chip_2
  target: pod_0/rack_0/board_3/chip_7
  type: c2c
- source: pod_0/rack_0/board_3/chip_3
  target: pod_0/rack_0/board_3/chip_4
  type: c2c
- source: pod_0/rack_0/board_3/chip_3
  target: pod_0/rack_0/board_3/chip_5
  type: c2c
- source: pod_0/rack_0/board_3/chip_3
  target: pod_0/rack_0/board_3/chip_6
  type: c2c
- source: pod_0/rack_0/board_3/chip_3
  target: pod_0/rack_0/board_3/chip_7
  type: c2c
- source: pod_0/rack_0/board_3/chip_4
  target: pod_0/rack_0/board_3/chip_5
  type: c2c
- source: pod_0/rack_0/board_3/chip_4
  target: pod_0/rack_0/board_3/chip_6
  type: c2c
- source: pod_0/rack_0/board_3/chip_4
  target: pod_0/rack_0/board_3/chip_7
  type: c2c
- source: pod_0/rack_0/board_3/chip_5
  target: pod_0/rack_0/board_3/chip_6
  type: c2c
- source: pod_0/rack_0/board_3/chip_5
  target: pod_0/rack_0/board_3/chip_7
  type: c2c
- source: pod_0/rack_0/board_3/chip_6
  target: pod_0/rack_0/board_3/chip_7
  type: c2c
- source: pod_0/rack_0/board_0
  target: pod_0/rack_0/board_1
  type: b2b
- source: pod_0/rack_0/board_0
  target: pod_0/rack_0/board_2
  type: b2b
- source: pod_0/rack_0/board_0
  target: pod_0/rack_0/board_3
  type: b2b
- source: pod_0/rack_0/board_1
  target: pod_0/rack_0/board_2
  type: b2b
- source: pod_0/rack_0/board_1
  target: pod_0/rack_0/board_3
  type: b2b
- source: pod_0/rack_0/board_2
  target: pod_0/rack_0/board_3
  type: b2b
